# Generated by Django 5.2.7 on 2025-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="croak",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
