# Generated by Django 5.2.7 on 2025-11-03 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0002_alter_croak_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="croak",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_croaks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="croak",
            name="image_url",
            field=models.URLField(max_length=400),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=140)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "twit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="croaks.croak"
                    ),
                ),
            ],
        ),
    ]
