# Generated by Django 5.2.7 on 2025-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0004_alter_comment_author_alter_comment_twit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="twit",
            new_name="croak",
        ),
        migrations.AlterField(
            model_name="croak",
            name="image_url",
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
