# Generated by Django 5.2.7 on 2025-11-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0005_rename_twit_comment_croak_alter_croak_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created"]},
        ),
    ]
