# Generated by Django 5.2.7 on 2025-11-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0006_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created"]},
        ),
    ]
