# Generated by Django 5.2.7 on 2025-11-25 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0007_alter_comment_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["-created"], name="croaks_comm_created_8f3b3a_idx"
            ),
        ),
    ]
