# Generated by Django 5.2.7 on 2025-11-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0008_comment_croaks_comm_created_8f3b3a_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="croaks_comm_created_8f3b3a_idx",
        ),
    ]
