# Generated by Django 5.2.7 on 2025-11-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("croaks", "0009_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="croak",
            options={"ordering": ["-created"]},
        ),
    ]
