# Generated by Django 5.2.7 on 2025-10-24 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two Star"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.restaurant",
            ),
        ),
    ]
