# Generated by Django 5.2.7 on 2025-10-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_rating_alter_review_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "One"), (2, "Two"), (3, "Three"), (4, "Four"), (5, "Five")]
            ),
        ),
    ]
